// DO NOT EDIT. Generated by scripts/generate_clients.py.
// contract-digest: sha256:8d1ec8c1ffbb9d7aa9361fbd498ea500230ff7daeeb60026be60493ea20a6216

export type RetryClass = "safe_read" | "idempotent_write" | "never";
export type IdempotencyPolicy = "required" | "optional" | "forbidden";

export interface ClientOperation {
  readonly operationId: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly pathTemplate: string;
  readonly contentType: string | null;
  readonly successStatuses: readonly number[];
  readonly retryClass: RetryClass;
  readonly idempotency: IdempotencyPolicy;
  readonly conditionalHeader: string | null;
  readonly streamingRequest: boolean;
  readonly streamingResponse: boolean;
}

export const contractDigest = "sha256:8d1ec8c1ffbb9d7aa9361fbd498ea500230ff7daeeb60026be60493ea20a6216" as const;
export const operations = [
  {
    "operationId": "createImport",
    "method": "POST",
    "pathTemplate": "/v1/imports",
    "contentType": "application/json",
    "successStatuses": [
      202
    ],
    "retryClass": "idempotent_write",
    "idempotency": "required",
    "conditionalHeader": null,
    "streamingRequest": false,
    "streamingResponse": false
  },
  {
    "operationId": "getAsset",
    "method": "GET",
    "pathTemplate": "/v1/assets/{asset_id}",
    "contentType": null,
    "successStatuses": [
      200,
      304
    ],
    "retryClass": "safe_read",
    "idempotency": "forbidden",
    "conditionalHeader": "If-None-Match",
    "streamingRequest": false,
    "streamingResponse": false
  },
  {
    "operationId": "searchAssets",
    "method": "POST",
    "pathTemplate": "/v1/search",
    "contentType": "application/json",
    "successStatuses": [
      200
    ],
    "retryClass": "safe_read",
    "idempotency": "optional",
    "conditionalHeader": null,
    "streamingRequest": false,
    "streamingResponse": false
  },
  {
    "operationId": "createClipboardManifest",
    "method": "POST",
    "pathTemplate": "/v1/clipboard/manifests",
    "contentType": "application/vnd.memebank.meme-clip+json",
    "successStatuses": [
      201
    ],
    "retryClass": "idempotent_write",
    "idempotency": "optional",
    "conditionalHeader": null,
    "streamingRequest": false,
    "streamingResponse": false
  },
  {
    "operationId": "listSyncEvents",
    "method": "GET",
    "pathTemplate": "/v1/sync/events",
    "contentType": null,
    "successStatuses": [
      200
    ],
    "retryClass": "safe_read",
    "idempotency": "forbidden",
    "conditionalHeader": null,
    "streamingRequest": false,
    "streamingResponse": false
  }
] as const satisfies readonly ClientOperation[];
