// DO NOT EDIT. Generated by scripts/generate_clients.py.
// contract-digest: sha256:8d1ec8c1ffbb9d7aa9361fbd498ea500230ff7daeeb60026be60493ea20a6216

enum RetryClass { safeRead, idempotentWrite, never }
enum IdempotencyPolicy { required, optional, forbidden }

final class ClientOperation {
  const ClientOperation({
    required this.operationId,
    required this.method,
    required this.pathTemplate,
    required this.contentType,
    required this.successStatuses,
    required this.retryClass,
    required this.idempotency,
    required this.conditionalHeader,
    required this.streamingRequest,
    required this.streamingResponse,
  });

  final String operationId;
  final String method;
  final String pathTemplate;
  final String? contentType;
  final List<int> successStatuses;
  final RetryClass retryClass;
  final IdempotencyPolicy idempotency;
  final String? conditionalHeader;
  final bool streamingRequest;
  final bool streamingResponse;
}

const contractDigest = "sha256:8d1ec8c1ffbb9d7aa9361fbd498ea500230ff7daeeb60026be60493ea20a6216";
const operations = <ClientOperation>[
  ClientOperation(
    operationId: "createImport",
    method: "POST",
    pathTemplate: "/v1/imports",
    contentType: "application/json",
    successStatuses: const [202],
    retryClass: RetryClass.idempotentWrite,
    idempotency: IdempotencyPolicy.required,
    conditionalHeader: null,
    streamingRequest: false,
    streamingResponse: false,
  ),
  ClientOperation(
    operationId: "getAsset",
    method: "GET",
    pathTemplate: "/v1/assets/{asset_id}",
    contentType: null,
    successStatuses: const [200, 304],
    retryClass: RetryClass.safeRead,
    idempotency: IdempotencyPolicy.forbidden,
    conditionalHeader: "If-None-Match",
    streamingRequest: false,
    streamingResponse: false,
  ),
  ClientOperation(
    operationId: "searchAssets",
    method: "POST",
    pathTemplate: "/v1/search",
    contentType: "application/json",
    successStatuses: const [200],
    retryClass: RetryClass.safeRead,
    idempotency: IdempotencyPolicy.optional,
    conditionalHeader: null,
    streamingRequest: false,
    streamingResponse: false,
  ),
  ClientOperation(
    operationId: "createClipboardManifest",
    method: "POST",
    pathTemplate: "/v1/clipboard/manifests",
    contentType: "application/vnd.memebank.meme-clip+json",
    successStatuses: const [201],
    retryClass: RetryClass.idempotentWrite,
    idempotency: IdempotencyPolicy.optional,
    conditionalHeader: null,
    streamingRequest: false,
    streamingResponse: false,
  ),
  ClientOperation(
    operationId: "listSyncEvents",
    method: "GET",
    pathTemplate: "/v1/sync/events",
    contentType: null,
    successStatuses: const [200],
    retryClass: RetryClass.safeRead,
    idempotency: IdempotencyPolicy.forbidden,
    conditionalHeader: null,
    streamingRequest: false,
    streamingResponse: false,
  ),
];
