#!/usr/bin/env python3
from __future__ import annotations

import json
from typing import Any


def pascal(value: str) -> str:
    parts: list[str] = []
    current = ""
    for char in value:
        if char in "_-":
            if current:
                parts.append(current)
                current = ""
        elif char.isupper() and current:
            parts.append(current)
            current = char
        else:
            current += char
    if current:
        parts.append(current)
    return "".join(part[:1].upper() + part[1:] for part in parts)


def rust(operations: list[dict[str, Any]], digest: str) -> str:
    variants = "\n".join(f"    {pascal(op['operation_id'])}," for op in operations)
    all_ops = ", ".join(f"OperationId::{pascal(op['operation_id'])}" for op in operations)
    retry = {"safe_read": "SafeRead", "idempotent_write": "IdempotentWrite", "never": "Never"}
    idem = {"required": "Required", "optional": "Optional", "forbidden": "Forbidden"}
    arms: list[str] = []
    for op in operations:
        content = "None" if op["request_content_type"] is None else f"Some({json.dumps(op['request_content_type'])})"
        conditional = "None" if op["conditional_header"] is None else f"Some({json.dumps(op['conditional_header'])})"
        statuses = ", ".join(map(str, op["success_statuses"]))
        arms.append(f'''            OperationId::{pascal(op['operation_id'])} => OperationMetadata {{
                operation_id: {json.dumps(op['operation_id'])},
                method: {json.dumps(op['method'])},
                path_template: {json.dumps(op['path_template'])},
                content_type: {content},
                success_statuses: &[{statuses}],
                retry_class: RetryClass::{retry[op['retry_class']]},
                idempotency: IdempotencyPolicy::{idem[op['idempotency_key']]},
                conditional_header: {conditional},
                streaming_request: {str(op['streaming_request']).lower()},
                streaming_response: {str(op['streaming_response']).lower()},
            }},''')
    return f'''// DO NOT EDIT. Generated by scripts/generate_clients.py.
// contract-digest: {digest}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RetryClass {{ SafeRead, IdempotentWrite, Never }}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IdempotencyPolicy {{ Required, Optional, Forbidden }}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OperationId {{
{variants}
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OperationMetadata {{
    pub operation_id: &'static str,
    pub method: &'static str,
    pub path_template: &'static str,
    pub content_type: Option<&'static str>,
    pub success_statuses: &'static [u16],
    pub retry_class: RetryClass,
    pub idempotency: IdempotencyPolicy,
    pub conditional_header: Option<&'static str>,
    pub streaming_request: bool,
    pub streaming_response: bool,
}}

pub const CONTRACT_DIGEST: &str = {json.dumps(digest)};
pub const ALL_OPERATIONS: &[OperationId] = &[{all_ops}];

impl OperationId {{
    pub const fn metadata(self) -> OperationMetadata {{
        match self {{
{chr(10).join(arms)}
        }}
    }}
}}
'''


def dart(operations: list[dict[str, Any]], digest: str) -> str:
    retry = {"safe_read": "safeRead", "idempotent_write": "idempotentWrite", "never": "never"}
    entries: list[str] = []
    for op in operations:
        content = "null" if op["request_content_type"] is None else json.dumps(op["request_content_type"])
        conditional = "null" if op["conditional_header"] is None else json.dumps(op["conditional_header"])
        entries.append(f'''  ClientOperation(
    operationId: {json.dumps(op['operation_id'])},
    method: {json.dumps(op['method'])},
    pathTemplate: {json.dumps(op['path_template'])},
    contentType: {content},
    successStatuses: const {json.dumps(op['success_statuses'])},
    retryClass: RetryClass.{retry[op['retry_class']]},
    idempotency: IdempotencyPolicy.{op['idempotency_key']},
    conditionalHeader: {conditional},
    streamingRequest: {str(op['streaming_request']).lower()},
    streamingResponse: {str(op['streaming_response']).lower()},
  ),''')
    return f'''// DO NOT EDIT. Generated by scripts/generate_clients.py.
// contract-digest: {digest}

enum RetryClass {{ safeRead, idempotentWrite, never }}
enum IdempotencyPolicy {{ required, optional, forbidden }}

final class ClientOperation {{
  const ClientOperation({{
    required this.operationId,
    required this.method,
    required this.pathTemplate,
    required this.contentType,
    required this.successStatuses,
    required this.retryClass,
    required this.idempotency,
    required this.conditionalHeader,
    required this.streamingRequest,
    required this.streamingResponse,
  }});

  final String operationId;
  final String method;
  final String pathTemplate;
  final String? contentType;
  final List<int> successStatuses;
  final RetryClass retryClass;
  final IdempotencyPolicy idempotency;
  final String? conditionalHeader;
  final bool streamingRequest;
  final bool streamingResponse;
}}

const contractDigest = {json.dumps(digest)};
const operations = <ClientOperation>[
{chr(10).join(entries)}
];
'''


def typescript(operations: list[dict[str, Any]], digest: str) -> str:
    payload = [{
        "operationId": op["operation_id"],
        "method": op["method"],
        "pathTemplate": op["path_template"],
        "contentType": op["request_content_type"],
        "successStatuses": op["success_statuses"],
        "retryClass": op["retry_class"],
        "idempotency": op["idempotency_key"],
        "conditionalHeader": op["conditional_header"],
        "streamingRequest": op["streaming_request"],
        "streamingResponse": op["streaming_response"],
    } for op in operations]
    return f'''// DO NOT EDIT. Generated by scripts/generate_clients.py.
// contract-digest: {digest}

export type RetryClass = "safe_read" | "idempotent_write" | "never";
export type IdempotencyPolicy = "required" | "optional" | "forbidden";

export interface ClientOperation {{
  readonly operationId: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly pathTemplate: string;
  readonly contentType: string | null;
  readonly successStatuses: readonly number[];
  readonly retryClass: RetryClass;
  readonly idempotency: IdempotencyPolicy;
  readonly conditionalHeader: string | null;
  readonly streamingRequest: boolean;
  readonly streamingResponse: boolean;
}}

export const contractDigest = {json.dumps(digest)} as const;
export const operations = {json.dumps(payload, indent=2)} as const satisfies readonly ClientOperation[];
'''
