// DO NOT EDIT. Generated by scripts/generate_clients.py.
// contract-digest: sha256:8d1ec8c1ffbb9d7aa9361fbd498ea500230ff7daeeb60026be60493ea20a6216

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RetryClass { SafeRead, IdempotentWrite, Never }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IdempotencyPolicy { Required, Optional, Forbidden }

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OperationId {
    CreateImport,
    GetAsset,
    SearchAssets,
    CreateClipboardManifest,
    ListSyncEvents,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OperationMetadata {
    pub operation_id: &'static str,
    pub method: &'static str,
    pub path_template: &'static str,
    pub content_type: Option<&'static str>,
    pub success_statuses: &'static [u16],
    pub retry_class: RetryClass,
    pub idempotency: IdempotencyPolicy,
    pub conditional_header: Option<&'static str>,
    pub streaming_request: bool,
    pub streaming_response: bool,
}

pub const CONTRACT_DIGEST: &str = "sha256:8d1ec8c1ffbb9d7aa9361fbd498ea500230ff7daeeb60026be60493ea20a6216";
pub const ALL_OPERATIONS: &[OperationId] = &[OperationId::CreateImport, OperationId::GetAsset, OperationId::SearchAssets, OperationId::CreateClipboardManifest, OperationId::ListSyncEvents];

impl OperationId {
    pub const fn metadata(self) -> OperationMetadata {
        match self {
            OperationId::CreateImport => OperationMetadata {
                operation_id: "createImport",
                method: "POST",
                path_template: "/v1/imports",
                content_type: Some("application/json"),
                success_statuses: &[202],
                retry_class: RetryClass::IdempotentWrite,
                idempotency: IdempotencyPolicy::Required,
                conditional_header: None,
                streaming_request: false,
                streaming_response: false,
            },
            OperationId::GetAsset => OperationMetadata {
                operation_id: "getAsset",
                method: "GET",
                path_template: "/v1/assets/{asset_id}",
                content_type: None,
                success_statuses: &[200, 304],
                retry_class: RetryClass::SafeRead,
                idempotency: IdempotencyPolicy::Forbidden,
                conditional_header: Some("If-None-Match"),
                streaming_request: false,
                streaming_response: false,
            },
            OperationId::SearchAssets => OperationMetadata {
                operation_id: "searchAssets",
                method: "POST",
                path_template: "/v1/search",
                content_type: Some("application/json"),
                success_statuses: &[200],
                retry_class: RetryClass::SafeRead,
                idempotency: IdempotencyPolicy::Optional,
                conditional_header: None,
                streaming_request: false,
                streaming_response: false,
            },
            OperationId::CreateClipboardManifest => OperationMetadata {
                operation_id: "createClipboardManifest",
                method: "POST",
                path_template: "/v1/clipboard/manifests",
                content_type: Some("application/vnd.memebank.meme-clip+json"),
                success_statuses: &[201],
                retry_class: RetryClass::IdempotentWrite,
                idempotency: IdempotencyPolicy::Optional,
                conditional_header: None,
                streaming_request: false,
                streaming_response: false,
            },
            OperationId::ListSyncEvents => OperationMetadata {
                operation_id: "listSyncEvents",
                method: "GET",
                path_template: "/v1/sync/events",
                content_type: None,
                success_statuses: &[200],
                retry_class: RetryClass::SafeRead,
                idempotency: IdempotencyPolicy::Forbidden,
                conditional_header: None,
                streaming_request: false,
                streaming_response: false,
            },
        }
    }
}
